# Generated by Django 3.0.2 on 2020-02-22 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddAccessory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('image', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AddPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('image', models.TextField()),
                ('price', models.FloatField()),
                ('colour', models.CharField(max_length=20)),
                ('height', models.FloatField()),
                ('width', models.FloatField()),
                ('os', models.CharField(max_length=20)),
                ('display', models.FloatField()),
                ('mainCamera', models.FloatField()),
                ('frontCamera', models.FloatField()),
                ('processor', models.CharField(max_length=20)),
                ('cpu', models.FloatField()),
                ('ram', models.IntegerField()),
                ('internalMemory', models.IntegerField()),
                ('fourG', models.BooleanField()),
                ('video', models.CharField(max_length=20)),
                ('battery', models.IntegerField()),
                ('descrption', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=120)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
