# Generated by Django 3.0.2 on 2020-02-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phonenumber',
            field=models.CharField(default='NONE', max_length=15),
        ),
    ]
