# Generated by Django 3.0.2 on 2020-02-23 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Phones', '0003_auto_20200222_1901'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
