# Generated by Django 3.0.3 on 2020-03-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phones', '0004_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addphone',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='addphone',
            name='width',
            field=models.IntegerField(),
        ),
    ]
