# Generated by Django 3.0.3 on 2020-03-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phones', '0005_auto_20200301_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addphone',
            name='processor',
            field=models.CharField(max_length=30),
        ),
    ]
