# Generated by Django 3.0.3 on 2020-03-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phones', '0007_auto_20200301_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addphone',
            name='fourG',
            field=models.BooleanField(),
        ),
    ]
