# Generated by Django 3.0.3 on 2020-03-01 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Phones', '0008_auto_20200301_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addphone',
            old_name='descrption',
            new_name='description',
        ),
    ]
