# Generated by Django 3.0.5 on 2020-04-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phones', '0009_auto_20200301_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='addphone',
            name='cpu_cores',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
